version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code 
    ports:
      - "8090:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A CeleryProject worker --loglevel=info
    volumes:
      - .:/code 
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A CeleryProject beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis


  redis:
    image: "redis:alpine"